version: '3'

services:
  ciao:
    image: brotandgames/ciao
    ports:
      - 9002:3000

  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9001:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  piwigo:
    image: piwigo:latest
    volumes:
      - piwigo:/app/piwigo
      
  nginx:
    image: nginx:alpine
    links:
      - php
    volumes:
      - piwigo:/var/www/app/piwigo
      - ${PWD}/.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  php:
    # image: php:7-fpm-alpine
    build: 
      context: .docker/php
    ports:
      - 9000:9000
    volumes:
      - piwigo:/var/www/app/piwigo
      - ${PWD}/.docker/php/modified.ini:/usr/local/etc/php/conf.d/modified.ini
      - ${PWD}/.docker/php/piwigo.conf:/usr/local/etc/php-fpm.d/www.conf

  db:
    image: mariadb:latest
    restart: always
    volumes:
      - ${PWD}/.data:/var/lib/mysql
      # - ${PWD}/strict.cnf:/etc/mysql/conf.d/strict.cnf
    environment:
      MYSQL_ROOT_PASSWORD: piwigo
      MYSQL_DATABASE: piwigo
      MYSQL_USER: canal
      MYSQL_PASSWORD: canal

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 9003:8080
  mysql_admin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: piwigo
    ports:
      - 9003:80

  smtp:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      MH_HOSTNAME": smtp
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /docker-volumes.d/mails
    volumes:
      - ${PWD}/.mails:/docker-volumes.d/mails

networks:
  default: {}

volumes:
  portainer_data:
  piwigo:
